### ISSUE TITLE
Mute function

### ISSUE THREAD

**Issue by chabbster** [peterdikant/xair-remote#1]
Hey, 
thank you for creating this project. It's working very fine, except the mute function. When I press one of the mute buttons, it only mutes the channel when I press the button. When I release the button, it unmutes the channel. Is there any way to keep the channel muted until I press the button again? 
I'm using the X-Touch Mini with an X-Air XR18 (firmware version 1.17). 

Thanks a lot! 👍 :)

**Comment by chabbster** [comment]
By the way, I have an idea for the second layer: May you cause use this for controlling the buses 1-6 when they are used for in-ear monitoring.

**Comment by peterdikant** [comment]
Hi Thomas,

I’m glad you like this project!

Use the included setup file for the X-Touch Mini. It will configure the device so that the buttons work correctly :)

Best regards
Peter

**Comment by chabbster** [comment]
Hi Peter,

thanks a lot for your help, works great :)
