### ISSUE TITLE
Assign own buttons configuration / change bin

### ISSUE THREAD

**Issue by RayEarth2162** [peterdikant/xair-remote#3]
Hi there - thanks for the awesome program. I'm using RPi now so it works (rather than windows). However is there any way to customise the button assignments / bin file?

**Comment by peterdikant** [comment]
Sure, you can do that with the mappings editor from Behringer. Download it from the Behringer website.

**Comment by RayEarth2162** [comment]
Thanks Peter. Sorry I'm completely new to this MIDI controller. 

I've downloaded the X-Touch Mini editor, looked at XR12 manual for the MIDI inputs, then assigned the knobs to the faders I require. Exported the bin and put the file into xair-remote directory. Ran your python script but it didn't change the button configuration.

I suspect I did not do the right things haha...

**Comment by peterdikant** [comment]
The bin file is meant for you to configure your x-touch to work with the script, not the other way around.
