### ISSUE TITLE
Detect when X-Touch Mini is disconnected

### ISSUE THREAD

**Issue by BeansIsFat** [peterdikant/xair-remote#7]
Would it be possible to detect when the X-Touch Mini is disconnected and close the program? I'm using systemd to launch xair-remote automatically on a Raspberry Pi that doesn't have a keyboard attached.

When the X-Touch Mini isn't connected at boot the service will periodically start xair-remote. Once it's connected, xair-remote launches successfully. But if the X-Touch Mini is disconnected, xair-remote continues to run. Since I don't have a keyboard attached, the only way to get everything working again is to restart the Raspberry Pi.

**Comment by peterdikant** [comment]
Good idea. I think this could be done by better exception handling. I will take a look at it.

**Comment by peterdikant** [comment]
So, I tried to add this feature and failed. Seems like the MIDI backend RTMidi does not detect device disconnects. There is even a issue tracked for this: https://github.com/micdah/RtMidi.Core/issues/18

A workaround would be to list available MIDI devices once in a while in a seperate thread and close the program if the device is no longer listed.

But then I realized that a disconnect does not affect the the app in any way. The mixer state is being tracked while the X-Touch is disconnected and when you reconnect the X-Touch you just need to switch layers to update the buttons and everything works just fine.

So maybe this is even better than closing the app.

**Comment by BeansIsFat** [comment]
I agree that using the layer buttons would be great and it works fine on Mac OS. Unfortunately, it doesn't seem to work on my Raspberry Pi with the latest Lite version of the OS. When I reconnect the X-Touch the MC Mode light turns on but it doesn't respond to any input.

Here are the version details:
Raspbian GNU/Linux 10 (buster)
Python 3.7.3

If there's a debug command I can run to get you more details about why this isn't working on Raspberry Pi OS please let me know.

**Comment by peterdikant** [comment]
No, there are not debug commands available.

But I will take a look with the Raspberry. Maybe it will throw some exceptions when a disconnect occurs. If not, I will add the above mentioned workaround which would be activated by a new command line parameter.

**Comment by peterdikant** [comment]
I added the monitoring feature. Works fine in Linux but does not detect disconnects on MacOS. I don't know about Windows.
